logging:
  level:
    com:
      example:
        redis:
          mapper: debug
spring:
  redis:
  #数据库索引(默认为0)
    database: 0
  #服务器地址
    host: localhost
  #Redis服务器连接端口
    port: 6379
    pool:
    lettuce:
      pool:
      #连接池最大连接数(使用负值表示没有限制)
        max-active: 8
       #连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1
        #连接池中最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
  #连接超时时间(毫秒)
    timeout: 0
  cache:
    ehcache:
      config: ehcache.xml

